### ISSUE TITLE
For multi-day events, such as holiday camps, use MultidayEvent

### ISSUE THREAD

**Issue by nickevansuk** [openactive/developer-microsite#17]
## Rule name
For multi-day events, such as holiday camps, use MultidayEvent

## Rule type
Validation error

## Rule check
Check that startDate and endDate are not more than 24 hours apart

## Rule hint
Multiday events should be specified using a MultidayEvent and eventSchedule where applicable

## Associated proposal or model reference
https://github.com/openactive/modelling-opportunity-data/issues/94

## Examples
- https://github.com/openactive/activation/issues/123

**Comment by ldodds** [comment]
There are lots of different types of multi day events. Courses, festivals, etc. We are discussing proposal to add more specific types to the data model.

My preference would be to keep the types as a means to flag more meaningful categories of event rather than those that just have a longer duration.

Closing this pending result of that discussion.
